#! /bin/bash
# overwrite: overwrites the specified filename with standard input

opath=$PATH
PATH=/bin:/usr/bin

case $# in
	0|1) echo 'Usage: overwrite filename' 1>&2; exit 2
esac

file=$1; shift;
new=/tmp/overwrite.$$.new
old=/tmp/overwrite.$$.old
trap 'rm -f $new $old; exit 2;' 1 2 15

if PATH=$opath "$@" >$new
then
	cp $file $old
	trap '' 1 2 15
	cp $new $file
else
	echo "overwrite: $1 failed, $file unchanged" 1>&2
	exit 1
fi

rm -rf $new $old
